--
-- PostgreSQL database dump
--

-- Dumped from database version 16.6 (Debian 16.6-1.pgdg120+1)
-- Dumped by pg_dump version 17.0

-- Started on 2025-01-05 17:03:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

-- CREATE SCHEMA public;


-- ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3427 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

-- COMMENT ON SCHEMA public IS 'standard public schema';


-- SET default_tablespace = '';

-- SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 32974)
-- Name: Categorias; Type: TABLE; Schema: public; Owner: curita
--

CREATE TABLE public."Categorias" (
    "Id" bigint NOT NULL,
    "Nombre" text NOT NULL
);


ALTER TABLE public."Categorias" OWNER TO curita;

--
-- TOC entry 216 (class 1259 OID 32973)
-- Name: Categorias_Id_seq; Type: SEQUENCE; Schema: public; Owner: curita
--

ALTER TABLE public."Categorias" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categorias_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 33003)
-- Name: DetalleInstrucciones; Type: TABLE; Schema: public; Owner: curita
--

CREATE TABLE public."DetalleInstrucciones" (
    "Id" bigint NOT NULL,
    "RecetaId" bigint NOT NULL,
    "Instruccion" text NOT NULL
);


ALTER TABLE public."DetalleInstrucciones" OWNER TO curita;

--
-- TOC entry 222 (class 1259 OID 33002)
-- Name: DetalleInstrucciones_Id_seq; Type: SEQUENCE; Schema: public; Owner: curita
--

ALTER TABLE public."DetalleInstrucciones" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DetalleInstrucciones_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 33016)
-- Name: IngredientesRecetas; Type: TABLE; Schema: public; Owner: curita
--

CREATE TABLE public."IngredientesRecetas" (
    "Id" bigint NOT NULL,
    "RecetaId" bigint NOT NULL,
    "Ingrediente" text NOT NULL,
    "Cantidad" text
);


ALTER TABLE public."IngredientesRecetas" OWNER TO curita;

--
-- TOC entry 224 (class 1259 OID 33015)
-- Name: IngredientesRecetas_Id_seq; Type: SEQUENCE; Schema: public; Owner: curita
--

ALTER TABLE public."IngredientesRecetas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."IngredientesRecetas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 33029)
-- Name: RecetaCategorias; Type: TABLE; Schema: public; Owner: curita
--

CREATE TABLE public."RecetaCategorias" (
    "Id" bigint NOT NULL,
    "RecetaId" bigint NOT NULL,
    "CategoriaId" bigint NOT NULL
);


ALTER TABLE public."RecetaCategorias" OWNER TO curita;

--
-- TOC entry 226 (class 1259 OID 33028)
-- Name: RecetaCategorias_Id_seq; Type: SEQUENCE; Schema: public; Owner: curita
--

ALTER TABLE public."RecetaCategorias" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RecetaCategorias_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 32990)
-- Name: Recetas; Type: TABLE; Schema: public; Owner: curita
--

CREATE TABLE public."Recetas" (
    "Id" bigint NOT NULL,
    "UsuarioId" bigint NOT NULL,
    "Nombre" text NOT NULL,
    "Descripcion" text,
    "FotoUrl" text,
    "TiempoPreparacion" integer,
    "NumeroPorciones" integer
);


ALTER TABLE public."Recetas" OWNER TO curita;

--
-- TOC entry 228 (class 1259 OID 33044)
-- Name: RecetasFavoritas; Type: TABLE; Schema: public; Owner: curita
--

CREATE TABLE public."RecetasFavoritas" (
    "UsuarioId" bigint NOT NULL,
    "RecetaId" bigint NOT NULL,
    "FechaFavorito" timestamp with time zone NOT NULL
);


ALTER TABLE public."RecetasFavoritas" OWNER TO curita;

--
-- TOC entry 220 (class 1259 OID 32989)
-- Name: Recetas_Id_seq; Type: SEQUENCE; Schema: public; Owner: curita
--

ALTER TABLE public."Recetas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Recetas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 32982)
-- Name: Usuarios; Type: TABLE; Schema: public; Owner: curita
--

CREATE TABLE public."Usuarios" (
    "Id" bigint NOT NULL,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "FechaRegistro" timestamp with time zone NOT NULL
);


ALTER TABLE public."Usuarios" OWNER TO curita;

--
-- TOC entry 218 (class 1259 OID 32981)
-- Name: Usuarios_Id_seq; Type: SEQUENCE; Schema: public; Owner: curita
--

ALTER TABLE public."Usuarios" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Usuarios_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 32968)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: curita
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO curita;

--
-- TOC entry 3410 (class 0 OID 32974)
-- Dependencies: 217
-- Data for Name: Categorias; Type: TABLE DATA; Schema: public; Owner: curita
--

COPY public."Categorias" ("Id", "Nombre") FROM stdin;
1	Desayunos
2	Entradas
3	Aperitivos
4	Sopas y caldos
5	Ensaladas
6	Platos principales
7	Guarniciones
8	Postres
\.


--
-- TOC entry 3416 (class 0 OID 33003)
-- Dependencies: 223
-- Data for Name: DetalleInstrucciones; Type: TABLE DATA; Schema: public; Owner: curita
--

COPY public."DetalleInstrucciones" ("Id", "RecetaId", "Instruccion") FROM stdin;
1	1	Mezclar el ají panca con el ajo, el sillao, la mostaza y el vinagre. Sazonar con sal, pimienta y comino al gusto.
2	1	Embadurnar las presas de pollo con la mezcla anterior y dejar macerar por una hora como mínimo.
3	1	En una olla a fuego medio, colocar las presas de pollo junto con el jugo de la marinada y el caldo. Cocinar por 20 minutos aproximadamente o hasta que el pollo esté listo.
4	1	Para el puré de papa, cocer las papas en agua con sal. Luego pelarlas y prensarlas cuando aún estén calientes.
5	1	En una olla a fuego medio, añadir la leche evaporada, la mantequilla y sal al gusto. Mover con una cuchara de palo hasta derretir la mantequilla.
6	1	Agregar la papa prensada y mezclar constantemente hasta adquirir la consistencia de puré.
7	1	Servir el pollo a la olla con el puré de papa. Acompañar con arroz blanco.
\.


--
-- TOC entry 3418 (class 0 OID 33016)
-- Dependencies: 225
-- Data for Name: IngredientesRecetas; Type: TABLE DATA; Schema: public; Owner: curita
--

COPY public."IngredientesRecetas" ("Id", "RecetaId", "Ingrediente", "Cantidad") FROM stdin;
1	1	Presas de pollo	4
2	1	Cucharadas de ají panca	4
3	1	Cucharada de sillao	1
4	1	Cucharaditas de mostaza	2
5	1	Cucharada de sillao	1
6	1	Tazas de caldo de pollo	2
7	1	Cucharadas de vinagre tinto	2
8	1	Papa amarilla	1/2 Kg
9	1	Leche Evaporada	400 ml
10	1	Mantequilla	100 gr
\.


--
-- TOC entry 3420 (class 0 OID 33029)
-- Dependencies: 227
-- Data for Name: RecetaCategorias; Type: TABLE DATA; Schema: public; Owner: curita
--

COPY public."RecetaCategorias" ("Id", "RecetaId", "CategoriaId") FROM stdin;
1	1	6
\.


--
-- TOC entry 3414 (class 0 OID 32990)
-- Dependencies: 221
-- Data for Name: Recetas; Type: TABLE DATA; Schema: public; Owner: curita
--

COPY public."Recetas" ("Id", "UsuarioId", "Nombre", "Descripcion", "FotoUrl", "TiempoPreparacion", "NumeroPorciones") FROM stdin;
1	1	Pollo a la Olla	Pollo a la olla con puré, un guiso con base de ají panca que se acompaña perfectamente con puré de papa.	https://cdn0.recetasgratis.net/es/posts/8/8/2/pollo_a_la_olla_peruano_77288_600.jpg	30	4
\.


--
-- TOC entry 3421 (class 0 OID 33044)
-- Dependencies: 228
-- Data for Name: RecetasFavoritas; Type: TABLE DATA; Schema: public; Owner: curita
--

COPY public."RecetasFavoritas" ("UsuarioId", "RecetaId", "FechaFavorito") FROM stdin;
\.


--
-- TOC entry 3412 (class 0 OID 32982)
-- Dependencies: 219
-- Data for Name: Usuarios; Type: TABLE DATA; Schema: public; Owner: curita
--

COPY public."Usuarios" ("Id", "Username", "Email", "PasswordHash", "FechaRegistro") FROM stdin;
1	Pedro	pedro@example.com	123456	2025-01-05 20:04:22.276666+00
\.


--
-- TOC entry 3408 (class 0 OID 32968)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: curita
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250105200422_CreandoBaseDeDatos	8.0.11
\.


--
-- TOC entry 3428 (class 0 OID 0)
-- Dependencies: 216
-- Name: Categorias_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: curita
--

SELECT pg_catalog.setval('public."Categorias_Id_seq"', 9, false);


--
-- TOC entry 3429 (class 0 OID 0)
-- Dependencies: 222
-- Name: DetalleInstrucciones_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: curita
--

SELECT pg_catalog.setval('public."DetalleInstrucciones_Id_seq"', 8, false);


--
-- TOC entry 3430 (class 0 OID 0)
-- Dependencies: 224
-- Name: IngredientesRecetas_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: curita
--

SELECT pg_catalog.setval('public."IngredientesRecetas_Id_seq"', 11, false);


--
-- TOC entry 3431 (class 0 OID 0)
-- Dependencies: 226
-- Name: RecetaCategorias_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: curita
--

SELECT pg_catalog.setval('public."RecetaCategorias_Id_seq"', 2, false);


--
-- TOC entry 3432 (class 0 OID 0)
-- Dependencies: 220
-- Name: Recetas_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: curita
--

SELECT pg_catalog.setval('public."Recetas_Id_seq"', 2, false);


--
-- TOC entry 3433 (class 0 OID 0)
-- Dependencies: 218
-- Name: Usuarios_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: curita
--

SELECT pg_catalog.setval('public."Usuarios_Id_seq"', 2, false);


--
-- TOC entry 3239 (class 2606 OID 32980)
-- Name: Categorias PK_Categorias; Type: CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."Categorias"
    ADD CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id");


--
-- TOC entry 3247 (class 2606 OID 33009)
-- Name: DetalleInstrucciones PK_DetalleInstrucciones; Type: CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."DetalleInstrucciones"
    ADD CONSTRAINT "PK_DetalleInstrucciones" PRIMARY KEY ("Id");


--
-- TOC entry 3250 (class 2606 OID 33022)
-- Name: IngredientesRecetas PK_IngredientesRecetas; Type: CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."IngredientesRecetas"
    ADD CONSTRAINT "PK_IngredientesRecetas" PRIMARY KEY ("Id");


--
-- TOC entry 3254 (class 2606 OID 33033)
-- Name: RecetaCategorias PK_RecetaCategorias; Type: CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."RecetaCategorias"
    ADD CONSTRAINT "PK_RecetaCategorias" PRIMARY KEY ("Id");


--
-- TOC entry 3244 (class 2606 OID 32996)
-- Name: Recetas PK_Recetas; Type: CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."Recetas"
    ADD CONSTRAINT "PK_Recetas" PRIMARY KEY ("Id");


--
-- TOC entry 3257 (class 2606 OID 33048)
-- Name: RecetasFavoritas PK_RecetasFavoritas; Type: CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."RecetasFavoritas"
    ADD CONSTRAINT "PK_RecetasFavoritas" PRIMARY KEY ("UsuarioId", "RecetaId");


--
-- TOC entry 3241 (class 2606 OID 32988)
-- Name: Usuarios PK_Usuarios; Type: CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."Usuarios"
    ADD CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id");


--
-- TOC entry 3237 (class 2606 OID 32972)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3245 (class 1259 OID 33059)
-- Name: IX_DetalleInstrucciones_RecetaId; Type: INDEX; Schema: public; Owner: curita
--

CREATE INDEX "IX_DetalleInstrucciones_RecetaId" ON public."DetalleInstrucciones" USING btree ("RecetaId");


--
-- TOC entry 3248 (class 1259 OID 33060)
-- Name: IX_IngredientesRecetas_RecetaId; Type: INDEX; Schema: public; Owner: curita
--

CREATE INDEX "IX_IngredientesRecetas_RecetaId" ON public."IngredientesRecetas" USING btree ("RecetaId");


--
-- TOC entry 3251 (class 1259 OID 33061)
-- Name: IX_RecetaCategorias_CategoriaId; Type: INDEX; Schema: public; Owner: curita
--

CREATE INDEX "IX_RecetaCategorias_CategoriaId" ON public."RecetaCategorias" USING btree ("CategoriaId");


--
-- TOC entry 3252 (class 1259 OID 33062)
-- Name: IX_RecetaCategorias_RecetaId; Type: INDEX; Schema: public; Owner: curita
--

CREATE INDEX "IX_RecetaCategorias_RecetaId" ON public."RecetaCategorias" USING btree ("RecetaId");


--
-- TOC entry 3255 (class 1259 OID 33064)
-- Name: IX_RecetasFavoritas_RecetaId; Type: INDEX; Schema: public; Owner: curita
--

CREATE INDEX "IX_RecetasFavoritas_RecetaId" ON public."RecetasFavoritas" USING btree ("RecetaId");


--
-- TOC entry 3242 (class 1259 OID 33063)
-- Name: IX_Recetas_UsuarioId; Type: INDEX; Schema: public; Owner: curita
--

CREATE INDEX "IX_Recetas_UsuarioId" ON public."Recetas" USING btree ("UsuarioId");


--
-- TOC entry 3259 (class 2606 OID 33010)
-- Name: DetalleInstrucciones FK_DetalleInstrucciones_Recetas_RecetaId; Type: FK CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."DetalleInstrucciones"
    ADD CONSTRAINT "FK_DetalleInstrucciones_Recetas_RecetaId" FOREIGN KEY ("RecetaId") REFERENCES public."Recetas"("Id") ON DELETE CASCADE;


--
-- TOC entry 3260 (class 2606 OID 33023)
-- Name: IngredientesRecetas FK_IngredientesRecetas_Recetas_RecetaId; Type: FK CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."IngredientesRecetas"
    ADD CONSTRAINT "FK_IngredientesRecetas_Recetas_RecetaId" FOREIGN KEY ("RecetaId") REFERENCES public."Recetas"("Id") ON DELETE CASCADE;


--
-- TOC entry 3261 (class 2606 OID 33034)
-- Name: RecetaCategorias FK_RecetaCategorias_Categorias_CategoriaId; Type: FK CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."RecetaCategorias"
    ADD CONSTRAINT "FK_RecetaCategorias_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES public."Categorias"("Id") ON DELETE CASCADE;


--
-- TOC entry 3262 (class 2606 OID 33039)
-- Name: RecetaCategorias FK_RecetaCategorias_Recetas_RecetaId; Type: FK CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."RecetaCategorias"
    ADD CONSTRAINT "FK_RecetaCategorias_Recetas_RecetaId" FOREIGN KEY ("RecetaId") REFERENCES public."Recetas"("Id") ON DELETE CASCADE;


--
-- TOC entry 3263 (class 2606 OID 33049)
-- Name: RecetasFavoritas FK_RecetasFavoritas_Recetas_RecetaId; Type: FK CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."RecetasFavoritas"
    ADD CONSTRAINT "FK_RecetasFavoritas_Recetas_RecetaId" FOREIGN KEY ("RecetaId") REFERENCES public."Recetas"("Id") ON DELETE CASCADE;


--
-- TOC entry 3264 (class 2606 OID 33054)
-- Name: RecetasFavoritas FK_RecetasFavoritas_Usuarios_UsuarioId; Type: FK CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."RecetasFavoritas"
    ADD CONSTRAINT "FK_RecetasFavoritas_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES public."Usuarios"("Id") ON DELETE CASCADE;


--
-- TOC entry 3258 (class 2606 OID 32997)
-- Name: Recetas FK_Recetas_Usuarios_UsuarioId; Type: FK CONSTRAINT; Schema: public; Owner: curita
--

ALTER TABLE ONLY public."Recetas"
    ADD CONSTRAINT "FK_Recetas_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES public."Usuarios"("Id") ON DELETE CASCADE;


-- Completed on 2025-01-05 17:03:40

--
-- PostgreSQL database dump complete
--

