services:
  recetasapi:
    image: msolari1589/recetasapi:v0.3
    container_name: recetasapi
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - database

  database:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: curita
      POSTGRES_PASSWORD: Joomla1
      POSTGRES_DB: Recetas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
volumes:
  postgres_data: